# Generated by Django 5.2.5 on 2025-11-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreationDomain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('show_on_homepage', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='domain_icons/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'creation_domain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationFosscategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('foss', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('status', models.IntegerField()),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('is_learners_allowed', models.IntegerField()),
                ('show_on_homepage', models.PositiveSmallIntegerField()),
                ('is_translation_allowed', models.IntegerField()),
                ('available_for_nasscom', models.IntegerField()),
                ('available_for_jio', models.IntegerField()),
                ('csc_dca_programme', models.IntegerField()),
                ('credits', models.PositiveSmallIntegerField()),
                ('is_fossee', models.IntegerField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='foss_icons/')),
            ],
            options={
                'db_table': 'creation_fosscategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationFosscategoryDomain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_primary', models.IntegerField()),
            ],
            options={
                'db_table': 'creation_fosscategorydomain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationLanguage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('user', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'creation_language',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'creation_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationTutorialdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'creation_tutorialdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreationTutorialresource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_content_id', models.IntegerField(db_column='common_content_id')),
                ('outline', models.TextField()),
                ('outline_user_id', models.IntegerField(db_column='outline_user_id')),
                ('outline_status', models.PositiveSmallIntegerField()),
                ('script', models.CharField(max_length=255)),
                ('script_user_id', models.IntegerField(db_column='script_user_id')),
                ('script_status', models.PositiveSmallIntegerField()),
                ('timed_script', models.CharField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('playlist_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('video_thumbnail_time', models.TimeField()),
                ('video_user_id', models.IntegerField(db_column='video_user_id')),
                ('video_status', models.PositiveSmallIntegerField()),
                ('status', models.PositiveSmallIntegerField()),
                ('version', models.PositiveSmallIntegerField()),
                ('hit_count', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_status', models.PositiveSmallIntegerField()),
                ('extension_status', models.PositiveIntegerField()),
                ('submissiondate', models.DateTimeField()),
                ('is_unrestricted', models.IntegerField()),
            ],
            options={
                'db_table': 'creation_tutorialresource',
                'managed': False,
            },
        ),
    ]
